<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.MongoDB.Driver" Version="9.1.0" />
		<PackageReference Include="RestSharp" Version="112.1.0" />
	</ItemGroup>

</Project>
