<Project ToolsVersion="15.0">
  <!--
    To update the version of Uno, you should instead update the Sdk version in the global.json file.

    See https://aka.platform.uno/using-uno-sdk for more information.
    See https://aka.platform.uno/using-uno-sdk#implicit-packages for more information regarding the Implicit Packages.
  -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
    <PackageVersion Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
    <PackageVersion Include="Microsoft.Maui.Core" Version="$(MauiVersion)" />
    <PackageVersion Include="AdamE.Google.iOS.SignIn" Version="8.0.0" />
    <PackageVersion Include="Plugin.Firebase.CloudMessaging" Version="3.1.2" />
    <PackageVersion Include="Xamarin.GooglePlayServices.Auth" Version="121.3.0.3" />
    <PackageVersion Include="Xamarin.AndroidX.Activity" Version="1.10.1.2" />
    <PackageVersion Include="Xamarin.MediaGallery" Version="3.0.0-preview" />
  </ItemGroup>
</Project>