<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-android;net10.0-ios</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net10.0-tizen</TargetFrameworks> -->

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>History.MobileClient</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<MauiXamlInflator>SourceGen</MauiXamlInflator>
		<Nullable>disable</Nullable>
		<LangVersion>preview</LangVersion>

		<!-- Display name -->
		<ApplicationTitle>히스토리</ApplicationTitle>
		<!-- App Identifier -->
		<ApplicationId>com.airtaxi.history</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0.72</ApplicationDisplayVersion>
		<ApplicationVersion>89</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">26.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
	</PropertyGroup>

	<!--<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android' and '$(Configuration)' == 'Release'">
		<UseMonoRuntime>false</UseMonoRuntime>
	</PropertyGroup>-->
	
	<PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-android' AND '$(Configuration)' == 'Release'">
		<AndroidEnableSGenConcurrent>true</AndroidEnableSGenConcurrent>
		<!--<EnableLLVM>True</EnableLLVM>
		<AndroidEnableProfiledAot>False</AndroidEnableProfiledAot>-->
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-android' AND '$(Configuration)' == 'Debug'">
		<!--<EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>-->
		<!--<AndroidEnableMarshalMethods>true</AndroidEnableMarshalMethods>-->
	</PropertyGroup>
	
	<PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-ios'">	
		<ProvisioningType>manual</ProvisioningType>
			<CodesignKey>Apple Distribution: Byeong-Su Kang (UP6EXS2HJJ)</CodesignKey>
			<CodesignProvision>History iOS (Dist)</CodesignProvision>
		<!--<CodesignKey>Apple Development: Created via API (VDW7YD8BQC)</CodesignKey>
		<CodesignProvision>VS: com.airtaxi.history Development</CodesignProvision>-->
	</PropertyGroup>
	
	<PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-ios' And '$(RuntimeIdentifier)' == 'iossimulator-arm64'">
		<CodesignEntitlements>Platforms\iOS\Entitlements.plist</CodesignEntitlements>
	</PropertyGroup>
	
	<PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
		<!-- The AndroidKeyStore property is used to specify if the application should be signed with a key store.
      If set to true, the AndroidSigningKeyStore, AndroidSigningStorePass, AndroidSigningKeyAlias and AndroidSigningKeyPass properties must be set.-->
		<AndroidKeyStore>true</AndroidKeyStore>
		<AndroidSigningKeyStore>signing.keystore</AndroidSigningKeyStore>
		<AndroidSigningStorePass>kck4156</AndroidSigningStorePass>
		<AndroidSigningKeyAlias>hoyo_ftp</AndroidSigningKeyAlias>
		<AndroidSigningKeyPass>kck4156</AndroidSigningKeyPass>
	</PropertyGroup>

	<ItemGroup>
		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\foreground.svg" Color="#fff112" BaseSize="256,256" TintColor="#594431" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\**" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>
	
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.png" Color="#fff112" BaseSize="1024,1024" ForegroundScale="0.7" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-ios'">
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.png" Color="#fff112" BaseSize="1024,1024" ForegroundScale="1" />
	</ItemGroup>
	
	<ItemGroup>
		<None Remove="Platforms\Android\Resources\xml\provider_paths.xml" />
		<AndroidResource Include="Platforms\Android\Resources\xml\provider_paths.xml" />
	</ItemGroup>
		
	<ItemGroup>
	  <AndroidEnvironment Include="Platforms\Android\GarbageCollector.txt" />
	</ItemGroup>

	<ItemGroup>
	  <GoogleServicesJson Include="google-services.json" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-ios'">
		<BundleResource Include="GoogleService-Info.plist" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="ViewModels\MentionStickerViewModel.cs" />
	</ItemGroup>

	<ItemGroup>
		<MauiXaml Update="ContentViews\DataTemplatePresenter.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="ContentViews\EditPost\StickerCollectionView.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="ContentViews\EditPost\TextContentView.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="ContentViews\EditPost\UserCollectionView.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\AddFriendsPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\CreateStickerPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\ImageEditorPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\MessagePage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\MessagesPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\ModerationRecordsPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\MorePage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\PollResultsPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\PollVotersPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\SearchPostsPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\IgnoredFriendsPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\DiscoveryOptionSelectUsersPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\EditCommentPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\EditPostPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\AppShell.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\FriendListPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\FullScreenMediaViewerPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\AppleLoginPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\KakaoStoryLoginPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\InAppBrowserPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\LoginPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\MainPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\NotificationsPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\BlockedFriendsPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\PendingFriendRequestsPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\PostPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\InteractionsPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\PublicPostPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\RegisterPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\SettingsPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\StickerDetailPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\StickersPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\TimelinePage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\UserPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\WaitingFriendRequestsPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\WriteMessagePage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\Comment.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\Friendship.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\Content.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\Media.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\PublicPost.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\Repost.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\Post.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\Interaction.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\Profile.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\SharedPost.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Dependencies\SpeakLink\SpeakLink\SpeakLink.csproj" />
		<ProjectReference Include="..\History.Commons\History.Commons.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-ios'">
		<PackageReference Include="AdamE.Google.iOS.SignIn" Version="8.0.0.4" />
	</ItemGroup>
	
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
	  <PackageReference Include="Xamarin.GooglePlayServices.Auth" Version="121.4.0.1" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="13.0.0" />
		<PackageReference Include="CommunityToolkit.Maui.MediaElement" Version="7.0.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="FFImageLoading.Maui" Version="1.3.2" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.20" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.1" />
		<PackageReference Include="Plugin.Firebase.CloudMessaging" Version="4.0.0" />
		<PackageReference Include="Syncfusion.Maui.ImageEditor" Version="32.1.21" />
		<PackageReference Include="Syncfusion.Maui.Toolkit" Version="1.0.8" />
		<PackageReference Include="UraniumUI.Icons.FontAwesome" Version="2.14.0" />
		<PackageReference Include="UraniumUI.Icons.MaterialSymbols" Version="2.14.0" />
		<PackageReference Include="UraniumUI.Material" Version="2.14.0" />
		<PackageReference Include="Xamarin.Build.Download" Version="0.11.4" />
		<PackageReference Include="Xamarin.MediaGallery" Version="3.0.0-preview" />
	</ItemGroup>
</Project>