<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-ios</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net9.0-tizen</TargetFrameworks> -->

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>History.MobileClient</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<LangVersion>preview</LangVersion>

		<!-- Display name -->
		<ApplicationTitle>히스토리</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.airtaxi.history</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">26.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
	</PropertyGroup>
	
	<PropertyGroup Condition="'$(TargetFramework)' == 'net9.0-android'">
		<!-- The AndroidKeyStore property is used to specify if the application should be signed with a key store.
      If set to true, the AndroidSigningKeyStore, AndroidSigningStorePass, AndroidSigningKeyAlias and AndroidSigningKeyPass properties must be set.-->
		<AndroidKeyStore>true</AndroidKeyStore>
		<AndroidSigningKeyStore>signing.keystore</AndroidSigningKeyStore>
		<AndroidSigningStorePass>kck4156</AndroidSigningStorePass>
		<AndroidSigningKeyAlias>hoyo_ftp</AndroidSigningKeyAlias>
		<AndroidSigningKeyPass>kck4156</AndroidSigningKeyPass>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.png" Color="#fff112" BaseSize="1024,1024" ForegroundScale="0.7" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\foreground.svg" Color="#fff112" BaseSize="1024,1024" TintColor="#594431" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\**" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="google-services.json" />
	</ItemGroup>

	<ItemGroup>
	  <GoogleServicesJson Include="google-services.json" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\History.Commons\History.Commons.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="ContentViews\EditPost\TextContentView.xaml.cs">
	    <DependentUpon>TextContentView.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Pages\AppShell.xaml.cs">
	    <DependentUpon>AppShell.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\Styles\Friendship.xaml.cs">
	    <DependentUpon>Friendship.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\Styles\Content.xaml.cs">
	    <DependentUpon>Content.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
		<MauiXaml Update="ContentViews\DataTemplatePresenter.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="ContentViews\EditPost\TextContentView.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\AddFriendsPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\EditPostPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\AppShell.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\FriendListPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\FullScreenMediaViewerPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\LoginPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\PendingFriendRequestsPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\PostPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\TimelinePage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\UserPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\WaitingFriendRequestsPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\Comment.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\Friendship.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\Content.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\Media.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\Post.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\Profile.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0-ios'">
		<PackageReference Include="Xamarin.Google.iOS.SignIn" Version="5.0.2.4" />
	</ItemGroup>
	
	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0-android'">
	  <PackageReference Include="Xamarin.GooglePlayServices.Auth" Version="121.3.0.1" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="11.2.0" />
		<PackageReference Include="CommunityToolkit.Maui.MediaElement" Version="6.0.2" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="FFImageLoading.Maui" Version="1.2.7" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.60" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.4" />
		<PackageReference Include="Microsoft.Maui.Controls.Foldable" Version="9.0.60" />
		<PackageReference Include="UraniumUI.Icons.FontAwesome" Version="2.11.1" />
		<PackageReference Include="UraniumUI.Icons.MaterialSymbols" Version="2.11.1" />
		<PackageReference Include="UraniumUI.Material" Version="2.11.1" />
		<PackageReference Include="Xamarin.MediaGallery" Version="3.0.0-preview" />
		<PackageReference Include="SpeakLink" Version="0.6.10" />
	</ItemGroup>
	
	<ItemGroup>
	  <None Update="Resources\Styles\Post.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </None>
	  <None Update="Resources\Styles\Profile.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </None>
	</ItemGroup>

</Project>
