<Project Sdk="Uno.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net9.0-android;net9.0-ios;net9.0-windows10.0.22621.0</TargetFrameworks>

        <OutputType>Exe</OutputType>
        <UnoSingleProject>true</UnoSingleProject>
        
        <LangVersion>preview</LangVersion>
        <RootNamespace>History.MobileClient</RootNamespace>
        <!-- Display name -->
        <ApplicationTitle>히스토리</ApplicationTitle>
        <!-- App Identifier -->
        <ApplicationId>com.airtaxi.history.test</ApplicationId>
        <!-- Versions -->
        <ApplicationDisplayVersion>1.0.42</ApplicationDisplayVersion>
        <ApplicationVersion>53</ApplicationVersion>
        <!-- Package Publisher -->
        <ApplicationPublisher>airtaxi</ApplicationPublisher>
        <!-- Package Description -->
        <Description>History.MobileClient powered by Uno Platform.</Description>
        <!--
      If you encounter this error message:

        error NETSDK1148: A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll.
        Please update to a newer .NET SDK in order to reference this assembly.

      This means that the two packages below must be aligned with the "build" version number of
      the "Microsoft.Windows.SDK.BuildTools" package above, and the "revision" version number
      must be the highest found in https://www.nuget.org/packages/Microsoft.Windows.SDK.NET.Ref.
    -->
        <!-- <WindowsSdkPackageVersion>10.0.22621.28</WindowsSdkPackageVersion> -->

        <!--
      UnoFeatures let's you quickly add and manage implicit package references based on the features you want to use.
      https://aka.platform.uno/singleproject-features
    -->
        <UnoFeatures>
            Material;
            MediaElement;
            Toolkit;
            MauiEmbedding;
        </UnoFeatures>

        <AndroidXActivityVersion>1.10.1.2</AndroidXActivityVersion>
        <AndroidXCollectionVersion>1.5.0.2</AndroidXCollectionVersion>
        
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">26.0</SupportedOSPlatformVersion>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)' == 'net9.0-ios'">
        <ProvisioningType>manual</ProvisioningType>
        <CodesignKey>Apple Distribution: Byeong-Su Kang (UP6EXS2HJJ)</CodesignKey>
        <CodesignProvision>History iOS (Dist)</CodesignProvision>
        <!--<CodesignKey>Apple Development: Created via API (VDW7YD8BQC)</CodesignKey>
		<CodesignProvision>VS: com.airtaxi.history Development</CodesignProvision>-->
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)' == 'net9.0-ios' And '$(RuntimeIdentifier)' == 'iossimulator-arm64'">
        <CodesignEntitlements>Platforms\iOS\Entitlements.plist</CodesignEntitlements>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)' == 'net9.0-android'">
        <!-- The AndroidKeyStore property is used to specify if the application should be signed with a key store.
      If set to true, the AndroidSigningKeyStore, AndroidSigningStorePass, AndroidSigningKeyAlias and AndroidSigningKeyPass properties must be set.-->
        <AndroidKeyStore>true</AndroidKeyStore>
        <AndroidSigningKeyStore>signing.keystore</AndroidSigningKeyStore>
        <AndroidSigningStorePass>kck4156</AndroidSigningStorePass>
        <AndroidSigningKeyAlias>hoyo_ftp</AndroidSigningKeyAlias>
        <AndroidSigningKeyPass>kck4156</AndroidSigningKeyPass>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="ViewModels\**" />
      <EmbeddedResource Remove="ViewModels\**" />
      <None Remove="ViewModels\**" />
    </ItemGroup>

    <ItemGroup>
        <GoogleServicesJson Include="google-services.json" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net9.0-ios'">
        <BundleResource Include="GoogleService-Info.plist" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net9.0-ios'">
		<PackageReference Include="Microsoft.Maui.Core" />
        <PackageReference Include="AdamE.Google.iOS.SignIn" />
        <PackageReference Include="Xamarin.MediaGallery" />
        <ProjectReference Include="..\History.Uno.MauiControls\History.Uno.MauiControls.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net9.0-android'">
		<PackageReference Include="Microsoft.Maui.Core" />
		<PackageReference Include="Xamarin.GooglePlayServices.Auth" />
        <PackageReference Include="Xamarin.AndroidX.Activity" VersionOverride="1.10.1.2" />
        <PackageReference Include="Xamarin.MediaGallery" />
        <ProjectReference Include="..\History.Uno.MauiControls\History.Uno.MauiControls.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\History.Commons\History.Commons.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Page Update="LoginPage.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Plugin.Firebase.CloudMessaging" />
    </ItemGroup>
</Project>
